// src/components/ui/NavBar.tsx
// ===============================
// Purpose: Top navigation bar. Renders different links based on the
//          logged-in user's role (admin vs regular user).
// ===============================
//
// ROLE-BASED STRUCTURE:
//   Regular user sees: Home, Restaurants, Profile, Orders, Cart, Logout
//   Admin sees:        Home, Dashboard, Profile, Logout
//   Not logged in:     Home, Login
//
// The links are generated by a single `getNavLinks()` function below
// so all role logic lives in one place. To change the menu, edit
// that function — both the desktop and mobile menus use it.
// ===============================

import {
    Menubar,
    MenubarContent,
    MenubarItem,
    MenubarMenu,
    MenubarTrigger,
} from "@radix-ui/react-menubar";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "./button";
import {
    Loader2,
    ShoppingCart,
    Menu as MenuIcon,
    User,
    HandPlatter,
    Utensils,
    LayoutDashboard,
    LogOut,
} from "lucide-react";
import {
    Avatar,
    AvatarFallback,
    AvatarImage,
} from "@radix-ui/react-avatar";
import {
    Sheet,
    SheetClose,
    SheetContent,
    SheetDescription,
    SheetHeader,
    SheetTitle,
    SheetTrigger,
} from "./sheet";
import { Separator } from "@radix-ui/react-separator";
import { useAuth } from "@/context/useAuth";
// `User` is also imported from lucide-react above (as the icon), so we alias
// the auth type to `AuthUser` to avoid a naming collision. The type is only
// used in this file as a type annotation for the `user` prop on the
// mobile-menu sub-component, so the alias is local to this file.
import { type User as AuthUser } from "@/context/auth-types";
// The theme toggle is its own component so the same code powers both
// the desktop dropdown and the mobile menu — one implementation,
// one place to maintain.
import { ThemeToggle } from "@/components/ThemeToggle";
import { useCart } from "@/context/useCart";
import { useState, type ComponentType } from "react";

// ============================================================
// TYPES
// ============================================================

// Describes one link in the navigation bar.
// `Dropdown` means it has a submenu (used for Dashboard)
interface NavLink {
    label: string;
    to: string;
    icon?: ComponentType<{ className?: string }>;   // optional icon for the mobile menu
    dropdown?: { label: string; to: string }[];     // optional submenu items
}

// ============================================================
// ROLE-BASED NAV LINKS — THE BRAIN OF THE NAVBAR
// ============================================================
// To change the menu, edit this function. Both desktop and mobile
// versions pull from this single source of truth.
const getNavLinks = (isAuthenticated: boolean, isAdmin: boolean): NavLink[] => {
    // Everyone (including guests) sees the Home link
    const baseLinks: NavLink[] = [
        { label: "Home", to: "/" },
    ];

    // Guests see only Home — Profile, Orders, etc. require login
    if (!isAuthenticated) {
        return baseLinks;
    }

    if (isAdmin) {
        // ==================== LOGGED-IN ADMIN VIEW ====================
        // Top nav for admin = just Home, Dashboard, Profile, Logout.
        // Admin-specific sub-pages (Orders, Restaurants, Menu, Users)
        // live in the admin sidebar that wraps those routes — the top
        // nav should be a single, unambiguous Dashboard link, not a
        // dropdown that re-exposes the sidebar's links.
        return [
            ...baseLinks,
            { label: "Dashboard", to: "/admin", icon: LayoutDashboard },
            { label: "Profile",   to: "/profile", icon: User },
        ];
    }

    // ==================== LOGGED-IN REGULAR USER VIEW ====================
    return [
        ...baseLinks,
        { label: "Restaurants", to: "/filterPage",   icon: Utensils },
        { label: "Profile",    to: "/profile",      icon: User },
        { label: "Orders",     to: "/order/status", icon: HandPlatter },
    ];
};

// ============================================================
// MAIN NAVBAR (desktop + mobile trigger)
// ============================================================
const NavBar = () => {
    // ----- Hooks -----
    const { user, isAuthenticated, logout } = useAuth();
    const { totalItems } = useCart();
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);

    // ----- Role detection -----
    // If not logged in, treat as a non-admin (guest) so the login button shows
    const isAdmin = isAuthenticated && user?.role === "admin";
    const navLinks = getNavLinks(isAuthenticated, !!isAdmin);

    // ----- Handlers -----
    const handleLogout = async () => {
        setLoading(true);
        try {
            await logout();
            navigate("/");
        } finally {
            setLoading(false);
        }
    };

    return (
        <header className="w-full bg-white shadow-md fixed top-0 left-0 z-50">
            <div className="flex justify-between items-center h-16 max-w-7xl mx-auto px-6">
                {/* Logo */}
                <Link to="/" className="text-2xl font-bold md:font-extrabold text-gray-600">
                    FlavorCourt
                </Link>

                {/* ============ DESKTOP NAV (hidden on mobile) ============ */}
                <nav className="hidden md:flex items-center gap-6 text-gray-700 font-medium">
                    {navLinks.map((link) =>
                        link.dropdown ? (
                            // Links with a dropdown submenu (Dashboard)
                            <Menubar key={link.to}>
                                <MenubarMenu>
                                    <MenubarTrigger className="cursor-pointer hover:text-gray-500">
                                        {link.label}
                                    </MenubarTrigger>
                                    <MenubarContent>
                                        {link.dropdown.map((sub) => (
                                            <Link key={sub.to} to={sub.to}>
                                                <MenubarItem>{sub.label}</MenubarItem>
                                            </Link>
                                        ))}
                                    </MenubarContent>
                                </MenubarMenu>
                            </Menubar>
                        ) : (
                            // Regular links
                            <Link key={link.to} to={link.to} className="hover:text-gray-500">
                                {link.label}
                            </Link>
                        )
                    )}
                </nav>

                {/* ============ RIGHT SIDE OF NAVBAR (hidden on mobile) ============ */}
                <div className="hidden md:flex items-center gap-4">
                    {/* Theme toggle — light / dark / system, persisted to
                        localStorage. Reusable component (see ThemeToggle). */}
                    <ThemeToggle />

                    {/* CART ICON — only shown to LOGGED-IN regular users.
                        Hidden for admins (no shopping) and guests (must log in first) */}
                    {isAuthenticated && !isAdmin && (
                        <Link to="/cart" className="relative cursor-pointer hover:text-gray-500" aria-label="Cart">
                            <ShoppingCart className="w-5 h-5" />
                            {totalItems > 0 && (
                                <span className="absolute -top-2 -right-2 text-[10px] h-4 min-w-4 px-1 bg-red-500 text-white rounded-full flex items-center justify-center font-bold">
                                    {totalItems}
                                </span>
                            )}
                        </Link>
                    )}

                    {/* LOGIN or LOGOUT, depending on auth state.
                        Logged-out users see a Login button. Logged-in
                        users see a Logout button (with a spinner while
                        the API call is in flight). The profile avatar
                        lives BELOW this block — only for logged-in
                        users. Previously a "?" was shown for guests
                        (the AvatarFallback default), which looked
                        broken, so we now only render the avatar when
                        there's a real user behind it. */}
                    {isAuthenticated ? (
                        loading ? (
                            <Button disabled className="bg-orange hover:bg-hoverOrange">
                                <Loader2 className="animate-spin w-4 h-4 mr-1" /> Logging out...
                            </Button>
                        ) : (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={handleLogout}
                                className="bg-orange hover:bg-hoverOrange"
                            >
                                <LogOut className="w-4 h-4 mr-1" />
                                Logout
                            </Button>
                        )
                    ) : (
                        <Link to="/login">
                            <Button className="bg-orange hover:bg-hoverOrange">Login</Button>
                        </Link>
                    )}

                    {/* Profile avatar — ONLY for logged-in users.
                        Wrapped in a Link to /profile so the avatar
                        itself is clickable (in addition to the
                        "Profile" link in the nav). Falls back to a
                        generic user icon when:
                          - no profile picture is set
                          - AND no fullname is set
                        so the avatar never shows the broken "?" char.

                        The Link wrapper has explicit `h-10 w-10` +
                        `inline-flex items-center justify-center` so
                        the avatar's natural 40×40 size is enforced
                        even when this Link sits inside a flex
                        container with `items-center` — without the
                        explicit size the Link was compressing to
                        less than 40px and `rounded-full` was
                        rendering as a small oval instead of a
                        proper circle. */}
                    {isAuthenticated && user && (
                        <Link
                            to="/profile"
                            aria-label="Open profile"
                            title={user.fullname || "Profile"}
                            className="h-10 w-10 inline-flex items-center justify-center rounded-full focus:outline-none focus:ring-2 focus:ring-orange-400 shrink-0"
                        >
                            <Avatar>
                                <AvatarImage src={user.profilePicture || ""} />
                                <AvatarFallback>
                                    {user.fullname
                                        ? user.fullname.substring(0, 2).toUpperCase()
                                        : <User className="w-4 h-4" />}
                                </AvatarFallback>
                            </Avatar>
                        </Link>
                    )}
                </div>

                {/* ============ MOBILE NAV (hidden on desktop) ============ */}
                <MobileNavbar
                    navLinks={navLinks}
                    isAuthenticated={isAuthenticated}
                    isAdmin={!!isAdmin}
                    totalItems={totalItems}
                    user={user}
                    onLogout={handleLogout}
                />
            </div>
        </header>
    );
};

export default NavBar;

// ============================================================
// MOBILE MENU (the slide-out from the right)
// ============================================================
const MobileNavbar = ({
    navLinks,
    isAuthenticated,
    isAdmin,
    totalItems,
    user,
    onLogout,
}: {
    navLinks: NavLink[];
    isAuthenticated: boolean;
    isAdmin: boolean;
    totalItems: number;
    user: AuthUser | null;
    onLogout: () => void;
}) => {
    return (
        <Sheet>
            <SheetTrigger asChild>
                <Button variant="ghost" size="icon" className="md:hidden">
                    <MenuIcon className="w-6 h-6 rounded-full text-black" />
                </Button>
            </SheetTrigger>
            <SheetContent side="right" className="text-white bg-gray-900">
                <SheetHeader>
                    <SheetTitle className="font-bold text-white">FoodCourt</SheetTitle>
                </SheetHeader>
                <Separator className="my-2" />
                <SheetDescription>Navigate the app</SheetDescription>

                {/* Main links (Home, Restaurants/Profile/Orders, Dashboard for admin) */}
                <div className="flex flex-col gap-4 mt-4">
                    {navLinks.map((link) => {
                        const Icon = link.icon;
                        if (link.dropdown) {
                            // Dashboard submenu — render each dropdown item
                            return (
                                <div key={link.to} className="flex flex-col gap-2">
                                    <div className="flex items-center gap-3 px-3 py-2 font-semibold text-orange-300">
                                        {Icon && <Icon className="w-5 h-5" />}
                                        {link.label}
                                    </div>
                                    {link.dropdown.map((sub) => (
                                        <Link
                                            key={sub.to}
                                            to={sub.to}
                                            className="pl-10 py-1.5 text-sm hover:text-gray-200"
                                        >
                                            {sub.label}
                                        </Link>
                                    ))}
                                </div>
                            );
                        }
                        return (
                            <Link
                                key={link.to}
                                to={link.to}
                                className="flex items-center gap-4 px-3 py-2 rounded-lg font-medium hover:text-gray-200"
                            >
                                {Icon && <Icon className="w-5 h-5" />}
                                <span>{link.label}</span>
                            </Link>
                        );
                    })}

                    {/* Cart link — only for logged-in regular users, not admins or guests */}
                    {isAuthenticated && !isAdmin && (
                        <Link
                            to="/cart"
                            className="flex items-center gap-4 px-3 py-2 rounded-lg font-medium hover:text-gray-200"
                        >
                            <ShoppingCart className="w-5 h-5" />
                            <span>Cart{totalItems > 0 ? ` (${totalItems})` : ""}</span>
                        </Link>
                    )}
                </div>

                {/* Footer: avatar + name + theme toggle + login/logout button.
                    Same gating rule as the desktop nav: the avatar is
                    ONLY shown for logged-in users. Guests see the
                    login button below with no broken "?" fallback. */}
                <div className="flex flex-col w-full gap-5 mt-6">
                    {isAuthenticated && user && (
                        <div className="flex flex-row items-center gap-2">
                            <Avatar>
                                <AvatarImage src={user.profilePicture || ""} />
                                <AvatarFallback>
                                    {user.fullname
                                        ? user.fullname.substring(0, 2).toUpperCase()
                                        : <User className="w-4 h-4" />}
                                </AvatarFallback>
                            </Avatar>
                            <h1 className="text-xl font-bold">
                                {user.fullname || "Profile"}
                            </h1>
                        </div>
                    )}

                    {/* Theme toggle on mobile too — same component, same
                        persistence. Just rendered inline instead of in a
                        dropdown bar. */}
                    <div className="flex items-center justify-between">
                        <span className="text-sm text-gray-600">Theme</span>
                        <ThemeToggle />
                    </div>

                    <SheetClose asChild>
                        {isAuthenticated ? (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={onLogout}
                                className="flex justify-center w-full bg-orange hover:bg-hoverOrange"
                            >
                                <LogOut className="w-4 h-4 mr-1" />
                                Logout
                            </Button>
                        ) : (
                            <Link to="/login" className="w-full">
                                <Button type="button" variant="outline" className="w-full bg-orange hover:bg-hoverOrange">
                                    Login
                                </Button>
                            </Link>
                        )}
                    </SheetClose>
                </div>
            </SheetContent>
        </Sheet>
    );
};